# Generated by Django 4.1.5 on 2023-01-31 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unid', models.CharField(blank=True, max_length=115, null=True)),
                ('birthdate', models.DateField()),
                ('deathdate', models.DateField(blank=True, null=True)),
                ('ssn', models.CharField(max_length=11)),
                ('drivers', models.CharField(max_length=9)),
                ('passport', models.CharField(max_length=11)),
                ('prefix', models.CharField(max_length=3)),
                ('first', models.CharField(max_length=30)),
                ('last', models.CharField(max_length=30)),
                ('suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('maiden', models.CharField(blank=True, max_length=30, null=True)),
                ('marital', models.CharField(max_length=1)),
                ('race', models.CharField(max_length=5)),
                ('ethnicity', models.CharField(max_length=12)),
                ('gender', models.CharField(max_length=1)),
                ('birthplace', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('county', models.CharField(max_length=30)),
                ('zip', models.CharField(max_length=5)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('healthcare_expenses', models.FloatField()),
                ('healthcare_coverage', models.FloatField()),
            ],
        ),
    ]
