# Generated by Django 4.1.5 on 2023-01-31 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('START', models.DateField()),
                ('STOP', models.DateField(blank=True, null=True)),
                ('PATIENT', models.CharField(max_length=110)),
                ('ENCOUNTER', models.CharField(max_length=110)),
                ('CODE', models.CharField(max_length=20)),
                ('DESCRIPTION', models.CharField(max_length=100)),
            ],
        ),
    ]
