# Generated by Django 4.1.5 on 2023-02-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_allergy'),
    ]

    operations = [
        migrations.CreateModel(
            name='medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('stop', models.DateTimeField()),
                ('patient', models.UUIDField()),
                ('payer', models.UUIDField()),
                ('encounter', models.UUIDField()),
                ('code', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('base_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payer_coverage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dispensers', models.PositiveSmallIntegerField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason_code', models.CharField(blank=True, max_length=20, null=True)),
                ('reason_description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
