# Generated by Django 4.1.5 on 2023-02-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_medication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='unid',
        ),
        migrations.AddField(
            model_name='patients',
            name='uuid',
            field=models.CharField(blank=True, max_length=115, null=True),
        ),
    ]
