# Generated by Django 4.1.5 on 2023-02-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_remove_patients_unid_patients_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='uuid',
            field=models.CharField(max_length=115, null=True),
        ),
    ]
