# Generated by Django 4.1.5 on 2023-02-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_careplan_condition_device_encounter_imaging_studies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='careplan',
            name='uuid',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='uuid',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='imaging_studies',
            name='uuid',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='organizations',
            name='uuid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payers',
            name='uuid',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='uuid',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='careplan',
            name='encounter',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='careplan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='careplan',
            name='patient',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='condition',
            name='encounter',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='condition',
            name='patient',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='device',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='device',
            name='encounter',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='patient',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='udi',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='imaging_studies',
            name='encounter',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='imaging_studies',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='imaging_studies',
            name='patient',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='immunization',
            name='code',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='medication',
            name='encounter',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='medication',
            name='patient',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='medication',
            name='payer',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='uuid',
            field=models.CharField(blank=True, max_length=115, null=True),
        ),
        migrations.AlterField(
            model_name='payers',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
