# Generated by Django 4.1.5 on 2023-02-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_careplan_uuid_encounter_uuid_imaging_studies_uuid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allergy',
            old_name='CODE',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='allergy',
            old_name='DESCRIPTION',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='allergy',
            old_name='ENCOUNTER',
            new_name='encounter',
        ),
        migrations.RenameField(
            model_name='allergy',
            old_name='PATIENT',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='allergy',
            old_name='START',
            new_name='start',
        ),
        migrations.RenameField(
            model_name='allergy',
            old_name='STOP',
            new_name='stop',
        ),
        migrations.AlterField(
            model_name='encounter',
            name='organization',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='patient',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='payer',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='provider',
            field=models.CharField(max_length=50),
        ),
    ]
