# Generated by Django 4.1.5 on 2023-02-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_rename_code_allergy_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careplan',
            name='uuid',
            field=models.CharField(max_length=55),
        ),
    ]
