# Generated by Django 4.1.5 on 2023-02-09 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_alter_careplan_uuid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='careplan',
        ),
    ]
