# Generated by Django 4.1.5 on 2023-02-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_delete_careplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='careplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=55)),
                ('start', models.DateField()),
                ('stop', models.DateField()),
                ('patient', models.CharField(max_length=55)),
                ('encounter', models.CharField(max_length=55)),
                ('code', models.CharField(max_length=8)),
                ('description', models.CharField(max_length=255)),
                ('reason_code', models.CharField(max_length=8)),
                ('reason_description', models.CharField(max_length=255)),
            ],
        ),
    ]
