# Generated by Django 4.1.5 on 2023-02-09 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0011_careplan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='encounter',
        ),
    ]
