# Generated by Django 4.1.5 on 2023-02-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0012_delete_encounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='encounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=20)),
                ('start', models.DateTimeField()),
                ('stop', models.DateTimeField()),
                ('patient', models.CharField(max_length=50)),
                ('organization', models.CharField(max_length=50)),
                ('provider', models.CharField(max_length=50)),
                ('payer', models.CharField(max_length=50)),
                ('encounter_class', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('base_encounter_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_claim_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payer_coverage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason_code', models.CharField(blank=True, max_length=20, null=True)),
                ('reason_description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
