# Generated by Django 4.1.5 on 2023-02-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0013_encounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observations',
            name='value',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='payer_transitions',
            name='ownership',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='payer_transitions',
            name='payer',
            field=models.CharField(max_length=36, null=True),
        ),
    ]
