# Generated by Django 4.1.5 on 2023-02-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0014_alter_observations_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergy',
            name='code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='allergy',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='allergy',
            name='encounter',
            field=models.CharField(max_length=110, null=True),
        ),
        migrations.AlterField(
            model_name='allergy',
            name='patient',
            field=models.CharField(max_length=110, null=True),
        ),
        migrations.AlterField(
            model_name='allergy',
            name='start',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='careplan',
            name='code',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='careplan',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='careplan',
            name='encounter',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='careplan',
            name='patient',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='careplan',
            name='reason_code',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='careplan',
            name='reason_description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='careplan',
            name='start',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='careplan',
            name='stop',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='careplan',
            name='uuid',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='condition',
            name='code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='condition',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='condition',
            name='encounter',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='condition',
            name='patient',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='condition',
            name='start',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='encounter',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='patient',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='udi',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='base_encounter_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='encounter_class',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='organization',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='patient',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='payer',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='payer_coverage',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='provider',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='stop',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='total_claim_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='uuid',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='imaging_studies',
            name='body_site_code',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='imaging_studies',
            name='body_site_description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='imaging_studies',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='imaging_studies',
            name='encounter',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='imaging_studies',
            name='modality_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='imaging_studies',
            name='modality_description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='imaging_studies',
            name='patient',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='imaging_studies',
            name='sop_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='imaging_studies',
            name='sop_description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='immunization',
            name='base_cost',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='immunization',
            name='code',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='immunization',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='immunization',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='immunization',
            name='encounter',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='immunization',
            name='patient',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='base_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='code',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='dispensers',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='encounter',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='patient',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='payer',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='payer_coverage',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='stop',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='observations',
            name='code',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='observations',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='observations',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='observations',
            name='encounter',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='observations',
            name='patient',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='observations',
            name='type',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='observations',
            name='units',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='observations',
            name='value',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='lon',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='revenue',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='state',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='utilization',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='zip',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='birthplace',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='county',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='drivers',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='ethnicity',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='first',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='gender',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='healthcare_coverage',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='healthcare_expenses',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='last',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='lon',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='marital',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='passport',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='prefix',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='race',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='ssn',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='state',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='zip',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='payer_transitions',
            name='end_year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='payer_transitions',
            name='patient',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='payer_transitions',
            name='start_year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='payers',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='payers',
            name='amount_covered',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='payers',
            name='amount_uncovered',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='payers',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payers',
            name='covered_encounters',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='payers',
            name='covered_immunizations',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='payers',
            name='covered_medications',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='payers',
            name='covered_procedures',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='payers',
            name='member_months',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='payers',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payers',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payers',
            name='qols_avg',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='payers',
            name='revenue',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='payers',
            name='state_headquartered',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payers',
            name='uncovered_encounters',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='payers',
            name='uncovered_immunizations',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='payers',
            name='uncovered_medications',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='payers',
            name='uncovered_procedures',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='payers',
            name='unique_customers',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='payers',
            name='zip',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='base_cost',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='code',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='encounter',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='patient',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='gender',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='lon',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='organization',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='speciality',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='utilization',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='zip',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='supplies',
            name='code',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='supplies',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='supplies',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='supplies',
            name='encounter',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='supplies',
            name='patient',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='supplies',
            name='quantity',
            field=models.FloatField(null=True),
        ),
    ]
